Experiment - 9

Name: Nakshatra Parshwanath

PRN: 25070123132

Tools for EDA - Study of Numpy Library

In [42]:
#Declaration of Numpy

import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

#Dimension of Array

print(a.ndim)
print(b.ndim)

#Shape of Array

print(a.shape)
print(b.shape)

#Datatype

print(a.dtype)
print(b.dtype)

#In-Built Functions using Numpy

print(np.zeros((2,3)))

print(np.ones((3,3)))

print(np.eye((3)))

print((np.arange(1,10,2)))

print((np.linspace(0,1,4)))

#Operations using Numpy

print(a+5)
print(b*2)

print(np.mean(a))

print(np.median(a))

print(np.min(a))

print(np.max(a))

print(np.sum(a))

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[  6  15  25  35  45  55 505]
[[ 2  4  6]
 [ 8 10 12]]
93.0
30.0
1
500
651
